import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import MyApp from "./App";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Todo */}
        <MyApp/>
      </main>
    </div>
  );
}
